/** @type {Readonly<Record<Locale, {remoteLocal?:string;}>>} */
export const javaTOCMap = {
    "en-US": {
      "what-is-programming-language": "What is Programming Language?",
      "types-of-programming-languages": "Types of programming languages",
      "java-introduction": "Java Introduction",
      "history-of-java": "History of Java",
      "principles-of-java": "Principles of Java",
      "java-installation": "Java Installation",
      "java-program-execution-flow": "Java Program Execution Flow",
      "jdk-vs-jre": "JDK vs JRE",
      "jvm-architecture": "JVM Architecture",
      "identifiers-keywords": "Identifiers & Keywords",
      "data-types": "Data Types",
      "variables": "Variables",
      "methods": "Methods",
      "arrays": "Arrays",
      "strings-handling": "Strings Handling",
      "object-oriented-principles": "Object Oriented Principles",
      "constructors": "Constructors",
      "interfaces": "Interfaces",
      "programs-related-to-oops": "Programs related to OOPs",
      "final-classes": "Final classes",
      "abstract-class": "Abstract Class",
      "exception-handling": "Exception handling",
      "multi-threading": "Multi-Threading",
      "concurrency-package": "Concurrency Package",
      "executor-framework": "Executor Framework",
      "synchronization": "Synchronization",
      "lock-mechanism": "Lock mechanism",
      "serialization": "Serialization",
      "wrapper-classes": "Wrapper classes",
      "auto-boxing,-un-boxing": "Auto Boxing, Un-Boxing",
      "java-memory-management": "Java Memory Management",
      "class-loader-implementation": "Class Loader Implementation",
      "variable-arguments": "Variable Arguments",
      "file-io-operations": "File IO Operations",
      "introduction-to-collection-framework": "Introduction to Collection Framework",
      "list": "List",
      "set": "Set",
      "map": "Map",
      "properties": "Properties",
      "internal-implementation-of-list-map-set": "Internal implementation of List, Map, Set",
      "java-8-features-introduction": "Java 8 Features Introduction",
      "lambda-expressions": "Lambda Expressions",
      "functional-interfaces": "Functional Interfaces",
      "default-static-methods": "Default & Static Methods",
      "method-references": "Method References",
      "date-and-time-api-changes": "Date and Time API changes",
      "stream-api": "Stream API",
      "optional-class": "Optional class",
      "spliterator": "SplIterator",
      "introduction-to-advanced-java": "Introduction to Advanced Java",
      "introduction-to-database": "Introduction to Database",
      "types-of-databases": "Types of databases",
      "database-environment-setup": "Database Environment Setup",
      "db-table-creation": "DB Table Creation",
      "table-altering": "Table Altering",
      "crud-operations-database": "CRUD Operations",
      "primary-keys": "Primary Keys",
      "foreign-keys": "Foreign Keys",
      "jdbc-introduction": "JDBC Introduction",
      "jdbc-api-details": "JDBC API Details",
      "jdbc-architecture": "JDBC Architecture",
      "jdbc-driver": "JDBC Driver",

      "driver-manager": "Driver Manager",
      "connection": "Connection",
      "statement": "Statement",
      "prepared-statement": "Prepared Statement",
      "callable-statement": "Callable Statement",
      "result-set": "Result Set",
      "what-is-dao-layer": "What is Dao Layer?",
      "steps-to-create-jdbc-application": "Steps to create JDBC Application",
      "jdbc-applications-development": "JDBC Applications Development",
      "crud-operations-jdbc": "CRUD Operations",
      "connection-pooling": "Connection Pooling",
      "most-common-exceptions-in-jdbc-apps": "Most common exceptions in JDBC apps",
      "servlets": "Servlets",
      "what-is-web-application": "What is web application?",
      "web-application-architecture": "Web application architecture",
      "client-server": "Client & Server",
      "http-protocol": "Http Protocol",
      "what-is-servlet": "What is Servlet?",
      "servlet-api": "Servlet API",
      "servlet-life-cycle": "Servlet Life Cycle",
      "steps-to-create-servlet": "Steps to create Servlet",
      "deployment-descriptor": "Deployment Descriptor",
      "servlet-interface": "Servlet interface",
      "generic-servlet-class": "Generic Servlet class",
      "httpservlet-class": "HttpServlet class",
      "httpservletrequest": "HttpServletRequest",
      "httpservletresponse": "HttpServletResponse",
      "servletconfig": "ServletConfig",
      "servletcontext": "ServletContext",
      "init-params": "Init Params",
      "context-params": "Context Params",
      "forms-development": "Forms development",
      "cookies": "Cookies",
      "hidden-variables": "Hidden variables",
      "session-tracking-in-servlets": "Session Tracking in Servlets",
      "jsp-": "JSP",
      "introduction-to-user-interface": "Introduction to User interface",
      "introduction-to-jsp": "Introduction to JSP",
      "servlets-vs.-jsp": "Servlets vs. JSP",
      "life-cycle-of-jsp": "Life Cycle of JSP",
      "jsp-implicit-objects": "JSP Implicit Objects",
      "jsp-directives": "JSP Directives",
      "jsp-scripting-elements": "JSP Scripting Elements",
      "mvc-architecture-introduction": "MVC Architecture Introduction",
  }
};